# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
#   - clang
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HeaZDHSIUkVtPxDyJS5bD7qesdyRZ21+RMPJRSyllC32AnilNHy3H17Y2hNDfBPaKWs4tkUZ1gej+TKAJkTKXAO/mknuD6OTk/95Zn3K4SV+CZiHDuES2Qq/LthzMKh35U16fF08VKHTP1sNHJ/mS8dDlk5DVO49RchfpgqrXLxVR/ie6T/LWWTKyZ8rP7f/DEXvc0cLK9mjahILVCzybKhMStOj2bZxOaFJV/5go1N3ThlmvpUQQm3iwKQAeEebPfyOK4+sevVwreXHnuuFslQZRVohdq9t1L9VMOPTf2opSx/jN74DojC4IZ9SgJtitCc7cclnNpuB0/BBm6sq87BCbvYC9B9YkP6vXDMWY/LAqznXpGYqrrwuc2TL/3Xg65nDQZBTvOWeS044ILRT/9sRjoITpJgFN98C8wkJ/xs7vwMV6+s4k7eHZ5pRRjHX2pWm7YQSa/RgGQmspPfYgwMXCVRudqlYjx1O6M9mAMSCfJBJjGBYjaqhLvi9JdLO9FAVfUUw3dvw4bk7YYqN0GXlIvN6iolJ2QqX7jWItXUkZHMLrxUs0InoYBeeSjC+99OUoah6d6/FPqWYpurL0wd8Ap8hTzAqGZ4Puy+RrhriumNnWOSw3FNOFaZz6mrG7dFxOmmPmFaPtXSkF0eASzEzy9tccfFhaQZUtDtFXBU="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

# Add missing packages needed for build
addons:
  apt:
    packages:
      - tree
  coverity_scan:
    project:
      name: "troglobit/jush"
      description: "just a useless shell"
    notification_email: troglobit@gmail.com
    build_command_prepend: "PKG_CONFIG_PATH=/tmp/lib/pkgconfig ./autogen.sh && ./configure"
    build_command: "make clean all"
    branch_pattern: dev

# Install build requirements from source
install:
  - wget https://github.com/troglobit/editline/releases/download/1.16.0/editline-1.16.0.tar.xz
  - tar xf editline-1.16.0.tar.xz
  - (cd editline-1.16.0 && ./configure --prefix=/tmp && make && make install-strip)

# Override default build command, we do not have `make test` yet
script:
  - ./autogen.sh
  - PKG_CONFIG_PATH=/tmp/lib/pkgconfig ./configure --disable-silent-rules --prefix=/tmp
  - make -j5
  - make install-strip
  - tree /tmp
  - ldd /tmp/bin/jush
  - LD_LIBRARY_PATH=/tmp/lib /tmp/bin/jush -h
